"documentation":
  - changed-files:
    - any-glob-to-any-file: ['**/{docs,doc,documentation}/**', '/*.md']

"platform:android":
  - changed-files:
    - any-glob-to-any-file: ['source/runtime/**/{android,unix}/**']

"platform:ios":
  - changed-files:
    - any-glob-to-any-file: ['source/runtime/**/{ios,apple,unix}/**']

"platform:linuxbsd":
  - changed-files:
    - any-glob-to-any-file: ['source/runtime/**/{linux,unix}/**']

"platform:macos":
  - changed-files:
    - any-glob-to-any-file: ['source/runtime/**/{macos,apple,unix}/**']

"platform:ps5":
  - changed-files:
    - any-glob-to-any-file: ['source/runtime/**/ps5/**']

"platform:switch":
  - changed-files:
    - any-glob-to-any-file: ['source/runtime/**/switch/**']

"platform:uwp":
  - changed-files:
    - any-glob-to-any-file: ['source/runtime/**/uwp/**']

"platform:visionos":
  - changed-files:
    - any-glob-to-any-file: ['source/runtime/**/{visionos,apple,unix}/**']

"platform:web":
  - changed-files:
    - any-glob-to-any-file: ['source/runtime/**/web/**']

"platform:windows":
  - changed-files:
    - any-glob-to-any-file: ['source/runtime/**/windows/**']

"platform:xbox":
  - changed-files:
    - any-glob-to-any-file: ['source/runtime/**/xbox/**']

"topic:animation":
  - changed-files:
    - any-glob-to-any-file: ['source/runtime/animation/**']

"topic:audio":
  - changed-files:
    - any-glob-to-any-file: ['source/runtime/audio/**']

"topic:buildsystem":
  - changed-files:
    - any-glob-to-any-file: ['**/CMakeLists.txt', '**/*.cmake', "toolchain/**", "CMakePresets.json"]

"topic:core":
  - changed-files:
    - any-glob-to-any-file: ['source/runtime/core/**']

"topic:maths":
  - changed-files:
    - any-glob-to-any-file: ['source/runtime/core/{public,private}/maths/**']

"topic:network":
  - changed-files:
    - any-glob-to-any-file: ['source/runtime/network/**']

"topic:platforms":
  - changed-files:
    - any-glob-to-any-file: ['source/runtime/core/{public,private}/platforms/**']

"topic:plugin":
  - changed-files:
    - any-glob-to-any-file: ['source/runtime/plugin/**', 'source/plugins/**']

"topic:rendering":
  - changed-files:
    - any-glob-to-any-file: ['source/runtime/{renderer,rhi}/**']

"topic:shaders":
  - changed-files:
    - any-glob-to-any-file: ['source/runtime/shaders/**', 'source/shaders/**']

"topic:tests":
  - changed-files:
    - any-glob-to-any-file: ['**/{tests,test}/**']

"topic:editor":
  - changed-files:
    - any-glob-to-any-file: ['source/launch/editor/**']

"topic:thirdparty":
  - changed-files:
    - any-glob-to-any-file: ['thirdparty/**']
